services:
  api:
    build: .
    ports:
      - "9090:8000"
    volumes:
      - ./modelos:/app/modelos
      - ./diccionarios:/app/diccionarios
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api